### ISSUE TITLE
Determine responsibilities for ML algorithms & Big Data platforms

### ISSUE THREAD

**Issue by rudongsu** [msep2019/MSEP_2019_1#23]
The research will apply two machine learning algorithms (Naive Bayes and SVMs) on two Big Data platforms (Hadoop and Spark).
Each team member has to choose one algorithm for one platform.

**Comment by gggggahead** [comment]
a) Anying Xiang: Naive Bayes on Spark
b) Rudong Su: Naive Bayes on Hadoop
c) Sicheng Xin: Support Vector Machine on Hadoop
d) Xueying Guo: Support Vector Machine on Spark
